name: Run Go tests and lint for mars-go-tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install allure-go dependencies
        run: |
          go get github.com/ozontech/allure-go/pkg/allure
          go get github.com/ozontech/allure-go/pkg/framework/provider
          go mod tidy

      - name: Restore dependencies
        run: go mod download

      - name: Run tests
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: go test ./... -v

      - name: Run golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./...
          
      - name: Set up Java (required by Allure CLI)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download and install Allure CLI
        run: |
            curl -L -o allure.tgz https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
            tar -xzf allure.tgz
            sudo mv allure-2.27.0 /opt/allure
            sudo ln -s /opt/allure/bin/allure /usr/local/bin/allure
            allure --version

      - name: Generate Allure report (if data exists)
        if: always()
        run: |
          if [ -d "test/allure-results" ] && [ "$(ls -A test/allure-results)" ]; then
            allure generate test/allure-results --clean -o test/allure-report
          else
            echo "No Allure results found, skipping report generation."
          fi

      - name: Upload Allure report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: test/allure-report

      - name: Upload test results (optional, for debugging)
        if: failure()
        run: |
          echo "Tests failed. Check logs above."